const actionTypes = {
  CHANGE_AUTH_STATUS: `CHANGE_AUTH_STATUS`,
  AUTHORIZE_USER: `AUTHORIZE_USER`,
  CHANGE_CITY: `CHANGE_CITY`,
  CHANGE_SORTING_TYPE: `CHANGE_SORTING_TYPE`,
  FETCH_OFFERS: `FETCH_OFFERS`,
  SET_ERROR: `SET_ERROR`,
  FETCH_OFFERS_ERROR: `FETCH_OFFERS_ERROR`,
};

export {actionTypes};
